# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - master
pr:
- master

pool:
  vmImage: 'ubuntu-16.04'

stages:
- stage: install_requirements
  jobs:
  - job: install_requirements
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.7'
    - script: sh initialize_project_settings.sh
      displayName: 'Initialization'
  - job: check_code_style_and_run_test
    steps:
    - script: make
      displayName: 'Running tests via pytest'
